name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - name: Generate Snake Animation
        uses: Platane/snk@main
        id: snake-gif
        with:
          github_user_name: cristovaoolegario
          svg_out_path: dist/github-contribution-grid-snake.svg
